[project]
name = "amp-sim"
version = "0.1.0"
description = "guitar amplifier simulation using neural networks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "auraloss>=0.4.0",
    "datetime>=6.0",
    "numpy>=2.4.2",
    "scipy>=1.17.1",
    "soundfile>=0.13.1",
    "torch>=2.10.0",
    "torchaudio>=2.11.0",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]
